title: Ziying's Personal Website
description: ""
baseurl: "" # for GitHub Pages, leave empty
url: "https://letterhead9600.github.io" # replace with your actual GitHub username

# Author info
author:
  name: Ziying Jian
  email: ziyjny@gmail.com

# Social links
social:
  github: letterhead9600
  linkedin: ziying-jian-741847217

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme


