title: Ziying's Personal Website
description: Amateaur
baseurl: "" # for GitHub Pages, leave empty
url: "https://letterhead9600.github.io" # replace with your actual GitHub username

# Author info
author:
  name: Ziying Jian
  email: ziyjny@gmail.com

# Social links
social:
  github: letterhead9600
  linkedin: ziying-jian-741847217

# Theme (Jekyll theme you're using)
theme: minima
